spring:
  application:
    name: BorrowService
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        cluster-name: Nanjing
#    # 将loadbalancer的nacos支持开启，集成Nacos负载均衡
#    loadbalancer:
#      nacos:
#        enabled: true