spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Whm18051964286
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: BookService
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        # 添加监控页面地址即可
        dashboard: localhost:8858
  session:
    # Session store type.
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379


seata:
  # 注册
  registry:
    # 使用Nacos
    type: nacos
    nacos:
      namespace: 8ab31473-b8fb-47c7-a8ef-c55ff4127c28
      server-addr: localhost:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
  # 配置
  config:
    type: nacos
    nacos:
      namespace: 8ab31473-b8fb-47c7-a8ef-c55ff4127c28
      server-addr: localhost:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP

